spring.application.name=rates
server.port=8554

# This makes SpringBoot think the env file is like another application.properties file
spring.config.import=optional:file:.env[.properties] 
logging.level.com.example.rates.service=INFO